# Generated by Django 6.0.6 on 2026-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type', models.CharField(choices=[('dc', 'DC'), ('ac', 'AC')], max_length=255)),
                ('cross_section_mm2', models.FloatField(default=0)),
                ('max_voltage', models.FloatField(default=0)),
                ('length_m', models.FloatField(default=0)),
                ('resistance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('estimated_power_kwp', models.FloatField(default=0)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('invalid', 'Invalid')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_pln', models.FloatField(default=0)),
                ('max_dc_voltage', models.FloatField(default=0)),
                ('mppt_min', models.FloatField(default=0)),
                ('mppt_max', models.FloatField(default=0)),
                ('mppt_count', models.PositiveIntegerField(default=1)),
                ('max_dc_power', models.FloatField(default=0)),
                ('phases', models.CharField(choices=[('single', 'Single'), ('three', 'Three')], max_length=255)),
                ('max_mppt_current', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PvModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power_watt', models.FloatField(default=0)),
                ('efficiency_percent', models.FloatField(default=0)),
                ('price_pln', models.FloatField(default=0)),
                ('height_cm', models.FloatField(default=0)),
                ('width_cm', models.FloatField(default=0)),
                ('voc', models.FloatField(default=0)),
                ('vmp', models.FloatField(default=0)),
                ('Imp', models.FloatField(default=0)),
                ('temperature_coefficient_percent_per_c', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PvString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mppt_channel', models.CharField(choices=[('mppt1', 'MPPT1'), ('mppt2', 'MPPT2'), ('mppt3', 'MPPT3'), ('mppt4', 'MPPT4')], max_length=255)),
                ('module_count', models.PositiveIntegerField(default=1)),
                ('voc_string_cold_status', models.CharField(choices=[('ok', 'OK'), ('too_high', 'Too high'), ('risk_margin', 'Risk margin'), ('undefined', 'Undefined')], default='undefined', max_length=255)),
                ('mppt_voltage_status', models.CharField(choices=[('ok', 'OK'), ('below_range', 'Below range'), ('above_range', 'Above range'), ('near_limit_low', 'Near limit low'), ('near_limit_high', 'Near limit high')], default='ok', max_length=255)),
                ('dc_current_status', models.CharField(choices=[('ok', 'OK'), ('over_limit', 'Over limit'), ('near_limit', 'Near limit')], default='ok', max_length=255)),
                ('temp_zone', models.CharField(choices=[('low_temp', 'Low temp (-25°C to -10°C)'), ('moderate', 'Moderate (-10°C to +5°C)'), ('standard', 'Standard (5°C to 25°C)'), ('high_temp', 'High temp (25°C+)')], default='standard', max_length=255)),
                ('cable_length_class', models.CharField(choices=[('short', 'Short (<10 m)'), ('medium', 'Medium (10–25 m)'), ('long', 'Long (25–50 m)'), ('extreme', 'Extreme (>50 m)')], default='short', max_length=255)),
                ('loss_status', models.CharField(choices=[('ok', 'OK'), ('acceptable', 'Acceptable'), ('high_loss', 'High loss'), ('critical', 'Critical')], default='ok', max_length=255)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('invalid', 'Invalid')], default='valid', max_length=255)),
                ('validation_code', models.CharField(choices=[('none', 'None'), ('voc_too_high', 'Voc too high'), ('mppt_out_of_range', 'MPPT out of range'), ('string_too_long', 'String too long'), ('current_exceeded', 'Current exceeded'), ('mismatch_module_type', 'Mismatch module type'), ('unknown_configuration', 'Unknown configuration')], default='none', max_length=255)),
                ('performance_tier', models.CharField(choices=[('optimal', 'Optimal'), ('good', 'Good'), ('suboptimal', 'Suboptimal'), ('poor', 'Poor')], default='good', max_length=255)),
            ],
        ),
    ]
