# Generated by Django 6.0.6 on 2026-06-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pv_elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='inverter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pv_elements.inverter'),
        ),
        migrations.AddField(
            model_name='pvstring',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='pv_elements.installation'),
        ),
        migrations.AddField(
            model_name='pvstring',
            name='module_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_strings', to='pv_elements.pvmodule'),
        ),
    ]
